---
- name: restart webserver
  service:
    name: "nginx"
    state: restarted
  notify: restart php-fpm
  when: php_enable_webserver

- name: restart php-fpm
  service:
    name: "php-fpm"
    state: restarted
  when: php_enable_php_fpm
